# version: '3.8'
 
# services: 
#   student_tracking_superadmin:
#     # image: mrajweb/student_tracking_superadmin:latest
#     build:
#       context: .
#     container_name: student_tracking_superadmin
#     restart: always
#     ports:
#       - 9741:9741
#     networks:
#       - student_tracking_superadmin-network
 
      
# networks:
#   student_tracking_superadmin-network:
#     driver: bridge